Finished translation of Fragment page
reactjs/uk.react.dev pull request #460
Opened 2023-04-27 19:50 UTC by syavik2001

Fragment.md page translation.

2023-05-04 12:29 UTC, Kamilius requested changes

2023-05-04 12:29 UTC, Kamilius commented on src/content/reference/react/Fragment.md
> +`<Fragment>`, часто використовується за допомогою синтаксису `<>...</>`, дозволяє групувати елементи без обгорткового вузла.
Ніколи не чув на практиці "обгортковий вузол". Можливо краще замінити на "елементу-обгортки"? Чи чогось по типу цього?

2023-05-08 23:38 UTC, syavik2001 commented
Згоден.
Виправив згідно вашим зауваженням.

2023-05-21 14:29 UTC, bkatsevych commented on src/content/reference/react/Fragment.md
> +Огорніть елементи у `<Fragment>` щоб групувати їх разом в ситуаціях, коли вам потрібен один елемент. Групування елементів у `Fragment` не впливає на результуючий DOM; це так само, як і якщо елементи
```suggestion
Огорніть елементи у `<Fragment>` щоб групувати їх разом в ситуаціях, коли вам потрібен один елемент. Групування елементів у `Fragment` не впливає на результуючий DOM; це так само, ніби елементи і не були згруповані. Переважно, порожній тег JSX `<></>` є скороченням для `<Fragment></Fragment>`.
```
На мій погляд таке формулювання є більш читабельним

2023-05-21 14:34 UTC, bkatsevych commented on src/content/reference/react/Fragment.md
> +- **необов’язковий** `ключ (key)`: Фрагменти, оголошені з явним синтаксисом `<Fragment>` можуть мати [ключі.](/learn/rendering-lists#keeping-list-items-in-order-with-key)
```suggestion
- **опційний** `key`: Фрагменти, оголошені з явним синтаксисом `<Fragment>` можуть мати [ключі.](/learn/rendering-lists#keeping-list-items-in-order-with-key)
```
_key_ повинен залишитися незмінним в цьому контексті. Ми ж не станемо перекладати HTML атрибути, наприклад.

2023-05-21 14:42 UTC, bkatsevych commented on src/content/reference/react/Fragment.md
> +Фрагменти є корисним інструментом, оскільки групування елементів з Фрагментом не має впливу на розташування або стилізацію, на відміну від огортання елементів в інший контейнер, такий як DOM-елемент.
```suggestion
Фрагменти є корисним інструментом, оскільки групування елементів з `Fragment` не має впливу на розташування або стилізацію, на відміну від огортання елементів в інший контейнер, такий як DOM-елемент. Якщо ви перевірите цей приклад за допомогою інструментів браузера, ви побачите, що всі DOM-вузли `<h1>` і `<p>` відображаються як сусідні елементи без обгорток навколо них:
```

2023-05-21 14:44 UTC, bkatsevych commented on src/content/reference/react/Fragment.md
> +Зазвичай вам не потрібно цього робити, якщо вам не треба [передавати ключ у ваш `Fragment`.](#rendering-a-list-of-fragments)
```suggestion
Зазвичай вам не потрібно цього робити, якщо вам не треба [передавати `key` у ваш `Fragment`.](#rendering-a-list-of-fragments)
```

Див. suggestion №2

2023-05-21 14:47 UTC, bkatsevych commented on src/content/reference/react/Fragment.md
> +Як і будь-який інший елемент, фрагменти можна присвоювати змінним, передавати їх як пропси тощо:
```suggestion
Як і будь-який інший елемент, `Fragment` елементи можна присвоювати змінним, передавати їх як пропси тощо:
```

2023-05-21 14:49 UTC, bkatsevych commented on src/content/reference/react/Fragment.md
> +Ось ситуація, коли вам потрібно явно написати `Fragment`, замість використання синтаксису `<></>`. Якщо ви [рендерите кілька елементів в циклі](/learn/rendering-lists), вам потрібно призначити `key`
```suggestion
Ось ситуація, коли вам потрібно написати `Fragment` явно, замість використання синтаксису `<></>`. Якщо ви [рендерите кілька елементів в циклі](/learn/rendering-lists), вам потрібно призначити `key` кожному елементу. Якщо елементи всередині циклу є Фрагментами, то вам потрібно використовувати звичайний синтаксис елементів JSX, щоб мати змогу вказати атрибут `key`:
```

2023-05-21 14:57 UTC, bkatsevych commented on src/content/reference/react/Fragment.md
> +Ви можете перевірити DOM, щоб переконатися, що навколо "дочірніх компонентів" Fragment немає огорнутих елементів:
```suggestion
Ви можете перевірити DOM, щоб переконатися, що дочірні компоненти Fragment нічим не обгортуються:
```
wrapper elements - елементи що обгорують, а не є обгорнутими (wrapped elements)

2023-05-21 15:08 UTC, bkatsevych approved these changes

2023-05-21 15:08 UTC, merged