Finished translation of hydrate page
reactjs/uk.react.dev pull request #503
Opened 2023-11-30 18:37 UTC by GeorgeShvab

2023-12-05 16:39 UTC, alinkedd commented on src/content/reference/react-dom/hydrate.md
> +Якщо атрибут або текстовий контент одного елемента неминуче відрізняється між сервером та клієнтом (наприклад, часова мітка), ви можете приглушити попередження про розбіжності під час гідрації.
```suggestion
Якщо атрибут або текстовий вміст хоча б одного елемента неминуче відрізняється між сервером та клієнтом (наприклад, часова мітка), ви можете приглушити попередження про розбіжності під час гідрації.
```

2023-12-05 16:39 UTC, alinkedd commented on src/content/reference/react-dom/hydrate.md
> +  був згенерований з App використовуючи react-dom/server.
те саме, що для рядків 85-86

2023-12-05 16:39 UTC, alinkedd commented on src/content/reference/react-dom/hydrate.md
> +Якщо вам потрібно відрендерити різний контент на сервері та клієнті, ви можете зробити двоетапний рендеринг. Компоненти, які рендерять щось інше на клієнті, можуть читати  [змінну стану](/reference/r
```suggestion
Якщо вам потрібно відрендерити різний контент на сервері та клієнті, ви можете зробити двоетапний рендеринг. Компоненти, які рендерять щось інше на клієнті, можуть використовувати [змінну стану](/reference/react/useState), наприклад `isClient`, яку ви можете змінити на `true` в [ефекті](/reference/react/useEffect):
```

2023-12-05 16:39 UTC, alinkedd commented on src/content/reference/react-dom/hydrate.md
> +  був згенерований з App використовуючи react-dom/server.
те саме, що для рядків 85-86

2023-12-05 16:39 UTC, alinkedd commented on src/content/reference/react-dom/hydrate.md
> +Таким чином, початковий рендер відрендерить контент такий же, як і на сервері, уникаючи розбіжностей. Однак, синхронно й одразу після гідрації відбудеться додатковий рендер.
```suggestion
Отже, початковий рендер відрендерить контент такий же, як і на сервері, уникаючи розбіжностей, однак, синхронно й одразу після гідрації відбудеться додатковий рендер.
```
зазвичай перекладаємо речення в речення
також про [таким чином](https://onlinecorrector.com.ua/uk/%D0%BE%D1%82%D0%B6%D0%B5-%D1%83-%D1%82%D0%B0%D0%BA%D0%B8%D0%B9-%D1%81%D0%BF%D0%BE%D1%81%D1%96%D0%B1/)

2023-12-05 16:39 UTC, alinkedd commented on src/content/reference/react-dom/hydrate.md
> +Цей підхід робить гідрацію повільнішою, тому що ваші компоненти рендеряться двічі. Пам'ятайте про користувацький досвід при повільному з'єднанні. JavaScript код може завантажитися значно пізніше ніж
```suggestion
Цей підхід сповільнює процес гідрації, тому що ваші компоненти рендеряться двічі. Пам'ятайте про користувацький досвід у разі повільного з'єднання. JavaScript-код може завантажитися значно пізніше, ніж відрендериться початковий HTML, тому рендер розбіжного UI одразу після гідрації може відчуватися для користувача різким.
```
p.s. використання [при](https://onlinecorrector.com.ua/uk/%D0%B1%D1%96%D0%BB%D1%8F-%D0%BA%D1%80%D0%B0%D0%B9-%D0%B7%D0%B0-%D0%BF%D1%96%D0%B4-%D1%87%D0%B0%D1%81-%D1%83-%D1%80%D0%B0%D0%B7%D1%96/)

2023-12-05 16:39 UTC, alinkedd commented on src/content/reference/react-dom/hydrate.md
> +Якщо вам потрібно відрендерити різний контент на сервері та клієнті, ви можете зробити двоетапний рендеринг. Компоненти, які рендерять щось інше на клієнті, можуть читати  [змінну стану](/reference/r
@bkatsevych 
content - вміст/наповнення (українське) чи контент (пряме запозичення)?
on the client/server or client-/server-side - на стороні клієнта/сервера чи на клієнті/сервері?
я за перші

2023-12-08 21:13 UTC, alinkedd commented
@bkatsevych глянь pr, як буде час

2023-12-10 21:45 UTC, bkatsevych requested changes
@alinkedd 
Перегляньте теж

2023-12-10 21:45 UTC, bkatsevych commented on src/content/reference/react-dom/hydrate.md
> +У React "гідрація" — це те, як React "прикріплюється" до наявного HTML, попередньо відрендереного у серверному оточенні за допомогою React. Під час гідрації React спробує додати слухачі подій до наяв
```suggestion
У React "гідрація" — це те, як React "прикріплюється" до наявного HTML, попередньо відрендереного у серверному середовищі за допомогою React. Під час гідрації React спробує додати слухачі подій до наявної розмітки та взяти на себе рендеринг застосунку на стороні клієнта.
```

2023-12-10 21:45 UTC, bkatsevych commented on src/content/reference/react-dom/hydrate.md
> +Цей підхід сповільнює процес гідрації, тому що ваші компоненти рендеряться двічі. Пам'ятайте про користувацький досвід у разі повільного з'єднання. JavaScript-код може завантажитися значно пізніше, н
```suggestion
Цей підхід сповільнює процес гідрації, тому що ваші компоненти рендеряться двічі. Пам'ятайте про досвід користувача у разі повільного з'єднання. JavaScript-код може завантажитися значно пізніше, ніж відрендериться початковий HTML, тому рендер іншого UI одразу після гідрації може відчуватися для користувача різким.
```

2023-12-11 21:53 UTC, alinkedd commented on src/content/reference/react-dom/hydrate.md
> +  return <h1>Привіт, світе!</h1>;
я поки закрию як non-essential, коли все перекладемо, до виправимо, щоб було однаково

2023-12-11 21:56 UTC, alinkedd commented
@GeorgeShvab я думаю, оці пару коментарів зверху і на "опційний" замінити, і буде чудово
ну і було б круто ребейзнути це на свіжий майстер і зісквошити коміти в один, бо не хочеться десятки комітів мержити

2023-12-17 16:51 UTC, GeorgeShvab commented
Замінив "необов'язковий" на "опційний"
Додав інші запропоновані виправлення
Зісквошив коміти в один

2023-12-22 22:50 UTC, bkatsevych approved these changes

2023-12-23 23:59 UTC, alinkedd commented on src/content/reference/react-dom/hydrate.md
>  <!--
```suggestion
```html public/index.html
<!--
```

2023-12-23 23:59 UTC, alinkedd commented on src/content/reference/react-dom/hydrate.md
> -```html public/index.html
виправила в https://github.com/reactjs/uk.react.dev/pull/503#discussion_r1435742054

2023-12-24 00:04 UTC, alinkedd approved these changes

2023-12-24 00:05 UTC, merged