Finished translation of Start a New React Project
reactjs/uk.react.dev pull request #547
Opened 2024-07-13 06:18 UTC by undead404

2024-07-14 12:43 UTC, alinkedd commented on src/content/learn/start-a-new-react-project.md
> +React можна користуватися без фреймворку, проте ми з'ясували, що більшість застосунків і сайтів, зрештою, розробляють рішення для поширених проблем, наприклад, розбиття коду, маршрутизації, отримання
Please retain two empty lines before this paragraph, as we need line-by-line parity between the original and translated text.

2024-07-16 17:31 UTC, undead404 commented on src/content/learn/start-a-new-react-project.md
> +React можна користуватися без фреймворку, проте ми з'ясували, що більшість застосунків і сайтів, зрештою, розробляють рішення для поширених проблем, наприклад, розбиття коду, маршрутизації, отримання
```suggestion

React можна користуватися без фреймворку, проте ми з'ясували, що більшість застосунків і сайтів, зрештою, розробляють рішення для поширених проблем, наприклад, розбиття коду, маршрутизації, отримання даних і генерування HTML. Ці проблеми – спільні для всіх бібліотек UI, а не лише для React.
```

2024-07-18 12:16 UTC, alinkedd commented on src/content/learn/start-a-new-react-project.md
> +App Router від Next.js також інтегрує [отримання даних із Suspense](/blog/2022/03/29/react-v18#suspense-in-data-frameworks). Це дає змогу задати стан завантаження (наприклад, заповнювач-скелет) для р
```suggestion
App Router від Next.js також інтегрує [отримання даних із Suspense](/blog/2022/03/29/react-v18#suspense-in-data-frameworks). Це дає змогу задати стан завантаження (наприклад, каркасний елемент для заповнення (skeleton placeholder)) для різних частин інтерфейсу безпосередньо в дереві React:
```

2024-07-18 12:24 UTC, alinkedd commented on src/content/learn/start-a-new-react-project.md
> +Серверні компоненти та Suspense — це радше можливості React, аніж можливості Next.js. Проте залучення їх на рівні фреймворку вимагає нетривіальних зусиль з реалізації. Наразі App Router Next.js — це
```suggestion
Серверні компоненти та Suspense — це радше функції React, аніж Next.js. Проте їхнє залучення на рівні фреймворку вимагає нетривіальних зусиль для реалізації. Наразі App Router Next.js — це найповніша імплементація. Команда React працює разом із розробниками бандлерів, щоб було легше реалізувати ці функції в наступному поколінні фреймворків.
```

2024-07-18 13:08 UTC, undead404 commented on src/content/learn/start-a-new-react-project.md
> +Навіть якщо вам спершу не потрібні маршрутизація чи отримання даних, то існує ймовірність того, що ви захочете додати для цих можливостей кілька бібліотек. Поки ваш згорток JavaScript розростатиметьс
бандл :-(

2024-07-18 13:12 UTC, undead404 commented on src/content/learn/start-a-new-react-project.md
> +**[Expo](https://expo.dev/) — це фреймворк React, що дає змогу створювати універсальні застосунки для Android, iOS і Вебу з по-справжньому нативним UI.** Він пропонує набір інструментів для [React Na
Зрада!

2024-07-18 13:13 UTC, undead404 commented on src/content/learn/start-a-new-react-project.md
> +Expo підтримується [Expo (компанією)](https://expo.dev/about). Розробляти застосунки за допомогою Expo можна безкоштовно, і їх можна подавати до каталогів застосунків Google і Apple без жодних обмеже
Можливо, все-таки краще подавати? Це ж фактично подання заявки

2024-07-18 13:13 UTC, undead404 commented on src/content/learn/start-a-new-react-project.md
> +## Найсвіжіші застоунки React {/*bleeding-edge-react-frameworks*/}
Комусь хотілось спати вже чи шо...

2024-07-18 13:14 UTC, undead404 commented on src/content/learn/start-a-new-react-project.md
> +Next.js підтримується [Vercel](https://vercel.com/). [Застосунок Next.js можна розгорнути](https://nextjs.org/docs/app/building-your-application/deploying) на будь-якому хостингу, що підтримує Node.j
```suggestion
Next.js підтримується командою [Vercel](https://vercel.com/). [Застосунок Next.js можна розгорнути](https://nextjs.org/docs/app/building-your-application/deploying) на будь-якому Node.js- або безсерверному хостингу, а також на власному сервері. Також Next.js підтримує [статичне експортування](https://nextjs.org/docs/app/building-your-application/deploying/static-exports), якому не потрібен сервер.
```

2024-07-18 16:08 UTC, alinkedd commented on src/content/learn/start-a-new-react-project.md
> +Expo підтримується [Expo (компанією)](https://expo.dev/about). Розробляти застосунки за допомогою Expo можна безкоштовно, і їх можна подавати до каталогів застосунків Google і Apple без жодних обмеже
ок
```suggestion
Expo підтримується [компанією Expo](https://expo.dev/about). Розробляти застосунки за допомогою Expo можна безкоштовно, і їх можна подавати до каталогів застосунків Google і Apple без жодних обмежень. На додачу Expo пропонує необов'язкові платні хмарні послуги.
```

2024-07-18 20:25 UTC, alinkedd requested changes

2024-07-18 20:25 UTC, alinkedd commented on src/content/learn/start-a-new-react-project.md
> +Якщо Expo - це для вас щось нове, перегляньте [підручник Expo](https://docs.expo.dev/tutorial/introduction/).
```suggestion
Якщо Expo — це для вас щось нове, перегляньте [підручник Expo](https://docs.expo.dev/tutorial/introduction/).
```

2024-07-18 20:25 UTC, alinkedd commented on src/content/learn/start-a-new-react-project.md
> +Під час досліджень заради подальшого покращення React ми усвідомили, що тісніша інтеграція React із фреймворками (а саме з маршрутизацією, згортанням і серверними технологіями) — це наша найбільша на
```suggestion
Під час досліджень заради подальшого покращення React ми усвідомили, що тісніша інтеграція React із фреймворками (а саме з маршрутизацією, згортанням і серверними технологіями) — це наша найбільша нагода допомогти користувачам React створювати кращі застосунки. Команда Next.js погодилася співпрацювати з нами щодо досліджень, розробки, інтегрування та тестування незалежних від фреймворків функцій React штибу [серверних компонентів React.](/blog/2023/03/22/react-labs-what-we-have-been-working-on-march-2023#react-server-components)
```

2024-07-18 20:27 UTC, alinkedd approved these changes

2024-07-18 20:28 UTC, merged