Finished translation of Editor Setup
reactjs/uk.react.dev pull request #548
Opened 2024-07-13 06:45 UTC by undead404

2024-07-14 12:38 UTC, alinkedd requested changes
Thanks for your effort!

Please, check these notes. Also you may want to change other PRs after reading them. That's why I'll do a thorough review for other PRs later.

2024-07-14 12:38 UTC, alinkedd commented on src/content/learn/editor-setup.md
> +Останнє, чого хочеться – щоб при взаємодії в коді з іншим розробником почалася суперечка про [табуляції проти пробілів](https://www.google.com/search?q=tabs+vs+spaces)! На щастя, [Prettier](https://p
- `Останнє, чого хочеться – щоб` -> `Не хотілося б, щоб`
- ми можемо змінювати посилання на український локалізований варіант за наявності. можливо, було б непогано змінити `https://www.google.com/search?q=tabs+vs+spaces` на `https://www.google.com.ua/search?q=%D1%82%D0%B0%D0%B1%D1%83%D0%BB%D1%8F%D1%86%D1%96%D1%8F+%D1%87%D0%B8+%D0%BF%D1%80%D0%BE%D0%B1%D1%96%D0%BB%D0%B8` чи схоже
- `для відповідності` -> `відповідно до`
- `налаштовним правилам` -> `конфігурованим правилам` (там, де config, configurable я би використовувала запозичення з тим же коренем, бо інакше змішаємо велику кількістю слів в одне слово `налаштування` - settings, configuration, setup, preset, etc.)
  - тому я б нижче писала `згідно з конфігурацією`
- `у випадку` -> `у разі` (https://onlinecorrector.com.ua/uk/%D1%83-%D1%80%D0%B0%D0%B7%D1%96/), але я б просто написала замість `У випадку ідеального налаштування` просто на `В ідеалі`, `Ідеально, коли`, `у найкращому варіанті`
- `застосовуючи свої редагування` -> `виправляючи замість вас`

2024-07-14 12:38 UTC, alinkedd commented on src/content/learn/editor-setup.md
> +1. Запустіть VS Code
```suggestion
1. Відкрийте VS Code
```

2024-07-14 12:38 UTC, alinkedd commented on src/content/learn/editor-setup.md
> +2. Скористайтеся Швидким відкриттям (натисніть Ctrl/Cmd+P)
```suggestion
2. Скористайтеся швидким відкриттям (натисніть Ctrl/Cmd+P)
```
нема потреби з великої тут писати

2024-07-14 12:38 UTC, alinkedd commented on src/content/learn/editor-setup.md
> +1. У VS Code натисніть `CTRL/CMD + SHIFT + P`.
```suggestion
1. Маючи відкрите вікно VS Code, натисніть `CTRL/CMD + SHIFT + P`.
```

2024-07-14 12:38 UTC, alinkedd commented on src/content/learn/editor-setup.md
> +5. Перевірте, що опція "format on save" має галочку!
```suggestion
5. Перевірте, що ввімкнено функцію "format on save"!
```
або
```suggestion
5. Перевірте, що вибрано опцію "format on save"!
```

2024-07-14 12:38 UTC, alinkedd commented on src/content/learn/editor-setup.md
> +> Якщо ваш набір налаштувань ESLint має правила форматування, то вони можуть конфліктувати з Prettier. Ми радимо вимикати всі правила форматування в наборах налаштувань ESLint за допомогою [`eslint-c
- `полювання на логічні помилки` -> `відловлювання помилок виконання/роботи коду`
- `Якщо ви хочете зробити форматування обов'язковим перед злиттям запиту на злиття` -> `Якщо ви хочете обов'язково форматувати файли у PR перед злиттям`
- `у` замість `в` перед `своїй` (https://ukr-mova.in.ua/library/orfografiya/cherguvannya-u-i-v)

2024-07-15 15:32 UTC, undead404 commented on src/content/learn/editor-setup.md
> +> Якщо ваш набір налаштувань ESLint має правила форматування, то вони можуть конфліктувати з Prettier. Ми радимо вимикати всі правила форматування в наборах налаштувань ESLint за допомогою [`eslint-c
```suggestion
> Якщо ваш набір налаштувань ESLint має правила форматування, то вони можуть конфліктувати з Prettier. Ми радимо вимикати всі правила форматування в наборах налаштувань ESLint за допомогою [`eslint-config-prettier`](https://github.com/prettier/eslint-config-prettier), щоб ESLint використовувався *лише* для відловлювання логічних помилок. Якщо ви хочете обов'язково форматувати файли у PR перед злиттям, використовуйте у своїй неперервній інтеграції [`prettier --check`](https://prettier.io/docs/en/cli.html#--check).
```

2024-07-15 15:36 UTC, undead404 commented
One more thing: у мене всюди довгі риски – :-)

2024-07-15 18:15 UTC, alinkedd commented on src/content/learn/editor-setup.md
> +* [Sublime Text](https://www.sublimetext.com/) має підтримку JSX і TypeScript, [підсвітку синтаксису](https://stackoverflow.com/a/70960574/458193) та вбудоване автодоповнення.
тут не згодна на розфарбовування
або підсвічування, або виділення кольором

https://uk.wikipedia.org/wiki/%D0%9F%D1%96%D0%B4%D1%81%D0%B2%D1%96%D1%87%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F_%D1%81%D0%B8%D0%BD%D1%82%D0%B0%D0%BA%D1%81%D0%B8%D1%81%D1%83

2024-07-15 18:18 UTC, alinkedd commented on src/content/learn/editor-setup.md
> +* [Vim](https://www.vim.org/) – це високоналаштовний текстовий редактор, розроблений для того, щоб зробити створення та внесення змін до текстів будь-якого роду дуже ефективним. У вигляді "vi" він до
Окей, тільки 'У вигляді' -> 'Як'

2024-07-15 18:28 UTC, alinkedd commented on src/content/learn/editor-setup.md
> +**Пересвідчіться, що ввімкнули у своєму проєкті всі правила [`eslint-plugin-react-hooks`](https://www.npmjs.com/package/eslint-plugin-react-hooks).** Вони критичні, адже зразу відловлюють найнеприємн
не згодна з обов'язковими, бо код можна і без них писати, правила теж можна свої писати, це не правильний відтінок essential тут

`є основними`, `є базовими`, `є ключовими`, `є стрижневими`

і тут прошу або додати є, або додати тире, щоб була або зупинка в мовленні, або розуміння закінченості, бо це важливий текст

2024-07-15 18:30 UTC, alinkedd commented on src/content/learn/editor-setup.md
> +Останнє, чого хочеться – щоб при взаємодії в коді з іншим розробником почалася суперечка про [табуляції проти пробілів](https://www.google.com/search?q=tabs+vs+spaces)! На щастя, [Prettier](https://p
при -> під час

2024-07-15 18:34 UTC, alinkedd commented on src/content/learn/editor-setup.md
> +> Якщо ваш набір налаштувань ESLint має правила форматування, то вони можуть конфліктувати з Prettier. Ми радимо вимикати всі правила форматування в наборах налаштувань ESLint за допомогою [`eslint-c
якщо хочеш залишити логіку, то `помилок логіки коду`, бо `логічна помилка` має декілька інших визначень, які можуть заплутати

2024-07-16 07:49 UTC, undead404 commented on src/content/learn/editor-setup.md
> +* [Sublime Text](https://www.sublimetext.com/) має підтримку JSX і TypeScript, [підсвітку синтаксису](https://stackoverflow.com/a/70960574/458193) та вбудоване автодоповнення.
Згодний на "підсвічування"

2024-07-16 07:49 UTC, undead404 commented on src/content/learn/editor-setup.md
> +* [Vim](https://www.vim.org/) – це високоналаштовний текстовий редактор, розроблений для того, щоб зробити створення та внесення змін до текстів будь-якого роду дуже ефективним. У вигляді "vi" він до
А якщо "під назвою"?

2024-07-16 07:49 UTC, undead404 commented on src/content/learn/editor-setup.md
> +> Якщо ваш набір налаштувань ESLint має правила форматування, то вони можуть конфліктувати з Prettier. Ми радимо вимикати всі правила форматування в наборах налаштувань ESLint за допомогою [`eslint-c
```suggestion
> Якщо ваш набір налаштувань ESLint має правила форматування, то вони можуть конфліктувати з Prettier. Ми радимо вимикати всі правила форматування в наборах налаштувань ESLint за допомогою [`eslint-config-prettier`](https://github.com/prettier/eslint-config-prettier), щоб ESLint використовувався *лише* для полювання на помилки логіки коду. Якщо ви хочете зробити форматування обов'язковим перед злиттям запиту на злиття, використовуйте в своїй неперервній інтеграції [`prettier --check`](https://prettier.io/docs/en/cli.html#--check).
```

2024-07-16 09:09 UTC, undead404 commented on src/content/learn/editor-setup.md
> +* [Vim](https://www.vim.org/) — це високоналаштовний текстовий редактор, розроблений для того, щоб зробити створення та внесення змін до текстів будь-якого роду дуже ефективним. У вигляді "vi" він до
```suggestion
* [Vim](https://www.vim.org/) — це багатий налаштуваннями текстовий редактор, розроблений для дуже ефективного створення та внесення змін до будь-яких текстів. Під назвою "vi" він доданий до більшості систем UNIX і до Apple OS X.
```

2024-07-16 09:49 UTC, alinkedd commented on src/content/learn/editor-setup.md
> +* [Vim](https://www.vim.org/) – це високоналаштовний текстовий редактор, розроблений для того, щоб зробити створення та внесення змін до текстів будь-якого роду дуже ефективним. У вигляді "vi" він до
ок

2024-07-16 09:49 UTC, alinkedd commented on src/content/learn/editor-setup.md
> +5. Перевірте, що опція "format on save" має галочку!
ок

2024-07-16 12:31 UTC, alinkedd approved these changes

2024-07-16 12:37 UTC, merged