Finished translation of Snate as a Snapshot
reactjs/uk.react.dev pull request #549
Opened 2024-07-14 09:43 UTC by undead404

2024-07-14 12:46 UTC, alinkedd commented on src/content/learn/state-as-a-snapshot.md
> -
Same about line-by-line parity https://github.com/reactjs/uk.react.dev/pull/547#discussion_r1677127928

2024-07-16 17:35 UTC, undead404 commented on src/content/learn/state-as-a-snapshot.md
```suggestion



```

2024-07-21 21:09 UTC, alinkedd requested changes
Перша частина. Закінчу пізніше, поки що думаю про снепшот

2024-07-21 21:09 UTC, alinkedd commented on src/content/learn/state-as-a-snapshot.md
> +* Чому стан не оновлюється зразу після його задання
зразу - калька
```suggestion
* Чому стан не оновлюється відразу після задання значення
```

2024-07-22 06:55 UTC, undead404 commented on src/content/learn/state-as-a-snapshot.md
> +title: Стан як зняток
Відбиток? Кадр?

2024-07-22 19:09 UTC, alinkedd commented on src/content/learn/state-as-a-snapshot.md
> +title: Стан як зняток
Нє, я би тут залишила снепшот або копія даних

2024-07-22 19:15 UTC, alinkedd commented on src/content/learn/state-as-a-snapshot.md
> +title: Стан як зняток
Але backup - це (резервна) копія даних, тому поки що снепшот (і додай заодно до словника у TRANSLATION).

снепшотів не багато серед файлів, так що потім за потреби змінимо

2024-07-22 19:16 UTC, alinkedd commented on src/content/learn/state-as-a-snapshot.md
> +title: Стан як зняток
```suggestion
title: Стан як снепшот
```

2024-07-22 21:30 UTC, alinkedd requested changes

2024-07-24 11:26 UTC, undead404 commented on src/content/learn/state-as-a-snapshot.md
> +title: Стан як зняток
Мені не подобається, тому що в такому вигляді ця назва нічого не говорить. Snapshot – це словникове слово англійської мови https://www.dictionary.com/browse/snapshot , яке саме в собі пояснює, яку природу має стан в React. А в українській цей трансліт не повідомляє геть нічого. Можливо, краще таки "кадр"?

2024-07-24 11:27 UTC, undead404 commented on src/content/learn/state-as-a-snapshot.md
> +Змінні стану можуть нагадувати звичайні змінні JavaScript, які можна зчитати та змінити. Проте стан поводиться радше як зняток. Задання йому значення не змінює наявну змінну стану, а натомість запуск
```suggestion
Змінні стану можуть нагадувати звичайні змінні JavaScript, які можна зчитати та змінити. Проте стан поводиться радше як снепшот — миттєвий знімок. Задання йому значення не змінює наявну змінну стану, а натомість запускає повторний рендер.
```
Можливо, хоча б так можна було б надати "снепшоту" якийсь зміст

2024-07-24 11:28 UTC, undead404 commented on src/content/learn/state-as-a-snapshot.md
> +## Рендеринг бере один зняток за раз {/*rendering-takes-a-snapshot-in-time*/}
```suggestion
## Рендеринг бере один снепшот за раз {/*rendering-takes-a-snapshot-in-time*/}
```

2024-07-24 11:29 UTC, undead404 commented on src/content/learn/state-as-a-snapshot.md
> +["Рендеринг"](/learn/render-and-commit#step-2-react-renders-your-components) означає, що React викликає ваш компонент, який є функцією. JSX, який ви повертаєте з цієї функції, — це як зняток UI в пев
По-моєму, копія без оригіналу це не дуже копія

2024-07-24 15:52 UTC, alinkedd commented on src/content/learn/state-as-a-snapshot.md
> +title: Стан як зняток
комп'ютер теж не говорив, але ж запозичили

кадр, по-моєму, французьке слово, не наше і запозичене, але розуміння прийшло згодом

2024-07-24 15:54 UTC, alinkedd commented on src/content/learn/state-as-a-snapshot.md
> +Змінні стану можуть нагадувати звичайні змінні JavaScript, які можна зчитати та змінити. Проте стан поводиться радше як зняток. Задання йому значення не змінює наявну змінну стану, а натомість запуск
тобто тут знімок ок, так?

2024-07-24 15:55 UTC, alinkedd commented on src/content/learn/state-as-a-snapshot.md
> +## Рендеринг бере один зняток за раз {/*rendering-takes-a-snapshot-in-time*/}
чому ти перекладаєш takes тут як бере?

2024-07-24 15:58 UTC, alinkedd commented on src/content/learn/state-as-a-snapshot.md
> +title: Стан як зняток
мені подобається кадр, бо є розкадрування і це щось схоже - окремий кадр із усього процесу. але можна використовувати кадр для пояснення, та не для технічної дефініції

2024-07-24 15:59 UTC, alinkedd commented on src/content/learn/state-as-a-snapshot.md
> +["Рендеринг"](/learn/render-and-commit#step-2-react-renders-your-components) означає, що React викликає ваш компонент, який є функцією. JSX, який ви повертаєте з цієї функції, — це як зняток UI в пев
отут згодна на кадр

2024-07-24 16:02 UTC, alinkedd commented on src/content/learn/state-as-a-snapshot.md
> +  const [to, setTo] = useState('Анна');
Аліса і Боб (якраз А і Б)

2024-07-24 16:02 UTC, alinkedd commented on src/content/learn/state-as-a-snapshot.md
> +  const [to, setTo] = useState('Анна');
точно не Анна (бо Ганна)

2024-07-24 16:02 UTC, undead404 commented on src/content/learn/state-as-a-snapshot.md
> +Змінні стану можуть нагадувати звичайні змінні JavaScript, які можна зчитати та змінити. Проте стан поводиться радше як зняток. Задання йому значення не змінює наявну змінну стану, а натомість запуск
Знімок, зняток, зліпок – варіанти, з яких мені до смаку припав саме зняток

Я розумію, що я цими додатковими варіантами наводжу тільки більший безлад, але я це роблю суто через те, що мені смертельно не подобається саме використання тут слова "копія", взагалі, й готовий пристати на різні варіанти

2024-07-24 16:02 UTC, undead404 commented on src/content/learn/state-as-a-snapshot.md
> +## Рендеринг бере один зняток за раз {/*rendering-takes-a-snapshot-in-time*/}
Бо тут треба перекласти речення, яке означає "В межах одного рендеру діє лише один снепшот-кадр-зняток-знімок стану". Що рендер робить зі снепшотом стану? Здається, бере

2024-07-24 16:03 UTC, undead404 commented
Повторюся в підсумку: нехай буде трансліт "снепшот", якщо ми його пояснимо без слова "копія". Частина стану копіюється, але снепшот сам не є копією

2024-07-24 16:04 UTC, undead404 commented on src/content/learn/state-as-a-snapshot.md
> +title: Стан як зняток
То давай тоді лишимо "снепшот" усюди по тексту, але в поясненні пояснимо через кадр

2024-07-24 16:12 UTC, alinkedd commented on src/content/learn/state-as-a-snapshot.md
> +title: Стан як зняток
давай

https://github.com/reactjs/uk.react.dev/pull/549#discussion_r1690071310 запозичую не особисто я, вже й інші, не маючи відповідника зрозумілого, використовували снепшот і снапшот

2024-07-24 16:12 UTC, alinkedd commented on src/content/learn/state-as-a-snapshot.md
> +title: Стан як зняток
якби ми були перші, то я би снепшот не вводила

2024-07-24 16:13 UTC, alinkedd commented on src/content/learn/state-as-a-snapshot.md
> +Змінні стану можуть нагадувати звичайні змінні JavaScript, які можна зчитати та змінити. Проте стан поводиться радше як зняток. Задання йому значення не змінює наявну змінну стану, а натомість запуск
тут на кадр

2024-07-24 16:19 UTC, alinkedd commented on src/content/learn/state-as-a-snapshot.md
> +## Рендеринг бере один зняток за раз {/*rendering-takes-a-snapshot-in-time*/}
takes це ще потребує, потрібно, забрати, приймати, знадобилось, вимірювати

Рендеринг бере один снепшот за раз - це дуже розмовно і виглядає дивно

2024-07-24 16:21 UTC, alinkedd commented on src/content/learn/state-as-a-snapshot.md
> +Змінні стану можуть нагадувати звичайні змінні JavaScript, які можна зчитати та змінити. Проте стан поводиться радше як зняток. Задання йому значення не змінює наявну змінну стану, а натомість запуск
чому один-єдиний, а не окремий?

2024-07-24 16:23 UTC, undead404 commented on src/content/learn/state-as-a-snapshot.md
> +Змінні стану можуть нагадувати звичайні змінні JavaScript, які можна зчитати та змінити. Проте стан поводиться радше як зняток. Задання йому значення не змінює наявну змінну стану, а натомість запуск
```suggestion
Змінні стану можуть нагадувати звичайні змінні JavaScript, які можна зчитати та змінити. Проте стан поводиться радше як снепшот – окремий незмінний кадр. Задання йому значення не змінює наявну змінну стану, а натомість запускає повторний рендер.
```
Нехай так

2024-07-24 17:31 UTC, alinkedd commented on src/content/learn/state-as-a-snapshot.md
> +Змінні стану можуть нагадувати звичайні змінні JavaScript, які можна зчитати та змінити. Проте стан поводиться радше як зняток. Задання йому значення не змінює наявну змінну стану, а натомість запуск
ок

2024-07-24 17:53 UTC, alinkedd commented on src/content/learn/state-as-a-snapshot.md
> +## Рендеринг бере один зняток за раз {/*rendering-takes-a-snapshot-in-time*/}
Ще Takes snapshot - сapture snapshot - створює снепшот/кадр/знімок або "зняв" або "взяв"


```suggestion
## Кожен рендер отримує новий снепшот {/*rendering-takes-a-snapshot-in-time*/}
```
aбо
```suggestion
## Кожен рендер створює новий снепшот {/*rendering-takes-a-snapshot-in-time*/}
```
або
```suggestion
## Для рендерингу потрібен новий снепшот {/*rendering-takes-a-snapshot-in-time*/}
```

2024-07-24 17:59 UTC, alinkedd commented on src/content/learn/state-as-a-snapshot.md
> +## Рендеринг бере один зняток за раз {/*rendering-takes-a-snapshot-in-time*/}
ChatGPT каже
Рендеринг фіксує знімок у часі
цікаво

2024-07-24 20:19 UTC, undead404 commented on src/content/learn/state-as-a-snapshot.md
> +["Рендеринг"](/learn/render-and-commit#step-2-react-renders-your-components) означає, що React викликає ваш компонент, який є функцією. JSX, який ви повертаєте з цієї функції, — це як зняток UI в пев
```suggestion
["Рендеринг"](/learn/render-and-commit#step-2-react-renders-your-components) означає, що React викликає ваш компонент, який є функцією. JSX, який ви повертаєте з цієї функції, — це як кадр UI в певну мить часу. Його пропси, обробники подій і локальні змінні обчислюються **з використанням його стану в мить рендеру.**
```

2024-07-25 12:37 UTC, alinkedd commented on src/content/learn/state-as-a-snapshot.md
> +  const [to, setTo] = useState('Анна');
а тут шо робимо?

2024-07-25 12:41 UTC, alinkedd requested changes

2024-07-25 12:41 UTC, alinkedd commented on TRANSLATION.md
> +| Місцевий  | _снепшоті_  | _снепшотах_  |
```suggestion
| Відмінок  | Однина                  | Множина      |
| --------- | ----------------------- | ------------ |
| Називний  | _снепшот_               | _снепшоти_   |
| Родовий   | _снепшоту_              | _снепшотів_  |
| Давальний | _снепшоту_/_снепшотові_ | _снепшотам_  |
| Знахідний | _снепшот_               | _снепшоти_   |
| Орудний   | _снепшотом_             | _снепшотами_ |
| Місцевий  | _снепшоті_/_cнепшотові_ | _снепшотах_  |
```

2024-07-25 12:45 UTC, alinkedd commented on src/content/learn/state-as-a-snapshot.md
> +  const [to, setTo] = useState('Анна');
ага, ти змінив, закриваю

2024-07-25 21:24 UTC, alinkedd approved these changes

2024-07-25 21:24 UTC, merged