Finished translation of Queueing a Series of State Updates
reactjs/uk.react.dev pull request #552
Opened 2024-07-19 08:00 UTC by undead404

2024-07-24 19:28 UTC, alinkedd requested changes

2024-07-24 19:28 UTC, alinkedd commented on src/content/learn/queueing-a-series-of-state-updates.md
> +Як щодо цього обробника подій? Як гадаєте, чим буде `number` у наступному рендері?
```suggestion
Як щодо цього обробника подій? Як гадаєте, яке значення матиме `number` у наступному рендері?
```

2024-07-24 19:28 UTC, alinkedd commented on src/content/learn/queueing-a-series-of-state-updates.md
> +### Що відбудеться, якщо оновити стан, спершу замінивши його {/*what-happens-if-you-update-state-after-replacing-it*/}
Знизу що станеться, тут що відбудеться.
вибери щось одне

2024-07-24 19:28 UTC, alinkedd commented on src/content/learn/queueing-a-series-of-state-updates.md
> +Підсумовуючи, ось як можна осмислити те, що передається до сетера стану `setNumber`:
```suggestion
Підсумовуючи, ось як можна осмислити те, що передається до функції задання стану `setNumber`:
```

2024-07-24 19:28 UTC, alinkedd commented on src/content/learn/queueing-a-series-of-state-updates.md
> +Коли обробник подій завершується, React запускає повторний рендер. Під час нього React обробляє чергу. Функції-оновлювачі запускаються під час рендерингу, тож **функції-оновлювачі повинні бути [чисти
```suggestion
Коли обробник подій завершується, React запускає повторний рендер. Під час нього React обробляє чергу. Функції-оновлювачі запускаються під час рендерингу, тож **функції-оновлювачі повинні бути [чистими](/learn/keeping-components-pure)** й лише *повертати* результат. Не намагайтеся задавати стан зсередини них чи запускати ще якісь побічні ефекти. У суворому режимі (strict mode) React намагається запустити кожну функцію-оновлювач двічі (відкидаючи другий результат), щоб допомогти з пошуком помилок.
```

додай strict mode як суворий режим до TRANSLATION файлу

2024-07-24 19:28 UTC, alinkedd commented on src/content/learn/queueing-a-series-of-state-updates.md
> +### Домовленості з найменування {/*naming-conventions*/}
```suggestion
### Домовленості про найменування {/*naming-conventions*/}
```

2024-07-24 19:28 UTC, alinkedd commented on src/content/learn/queueing-a-series-of-state-updates.md
> +Якщо вам подобається розлогіший код, то іншим прийнятим підходом є повторити повну назву змінної стану, так `setEnabled(enabled => !enabled)`, або скористатися префіксом так `setEnabled(prevEnabled =
```suggestion
Якщо вам подобається розлогіший код, то іншим прийнятим підходом є повторити повну назву змінної стану, як `setEnabled(enabled => !enabled)`, або скористатися префіксом, як `setEnabled(prevEnabled => !prevEnabled)`.
```

2024-07-24 19:28 UTC, alinkedd commented on src/content/learn/queueing-a-series-of-state-updates.md
> +* Задання стану не змінить змінної в наявному рендері, проте зробить запит щодо нового рендеру.
```suggestion
* Задання стану не змінить її змінну в наявному рендері, проте зробить запит щодо нового рендеру.
```

2024-07-24 19:28 UTC, alinkedd commented on src/content/learn/queueing-a-series-of-state-updates.md
> +Ви працюєте над застосунком мистецького торгівельного майданчика, що дає користувачам змогу розміщати кілька замовлень щодо одного предмету мистецтва водночас. Щоразу, коли користувач натискає кнопку
Може Очікує, а не Очікування?

2024-07-24 19:28 UTC, alinkedd commented on src/content/learn/queueing-a-series-of-state-updates.md
> +Чому так відбувається? Виправмо обидва лічильники.
```suggestion
Чому так відбувається? Виправіть обидва лічильники.
```

2024-07-24 19:28 UTC, alinkedd commented on src/content/learn/queueing-a-series-of-state-updates.md
> +Так можна пересвідчитись, що коли інкрементується чи декрементується лічильник, це відбувається щодо його *останнього* стану, а не того, яким стан був під час клацання.
```suggestion
Так можна пересвідчитись, що коли інкрементується чи декрементується лічильник, це відбувається відповідно до його *останнього* стану, а не того, яким стан був під час клацання.
```

2024-07-24 19:28 UTC, alinkedd commented on src/content/learn/queueing-a-series-of-state-updates.md
> +#### Самостійна реалізація черги стану {/*implement-the-state-queue-yourself*/}
```suggestion
#### Створення власної черги стану {/*implement-the-state-queue-yourself*/}
```

2024-07-24 19:28 UTC, alinkedd commented on src/content/learn/queueing-a-series-of-state-updates.md
> +Погортайте живий зразок. Зверніть увагу на те, що він демонструє **чотири тестові випадки.** Вони відповідають прикладам, які ви бачили на цій сторінці вище. Ваше завдання — реалізувати функцію `getF
```suggestion
Погортайте попередньо "пісочницю". Зверніть увагу на те, що у ній показані **чотири тестові випадки.** Вони відповідають прикладам, які ви бачили на цій сторінці вище. Ваше завдання — реалізувати функцію `getFinalState` так, щоб вона повертала коректний результат для кожного з цих випадків. Якщо реалізувати її коректно, то всі чотири тести пройдуть.
```

(перед цим sandbox перекладали як пісочницю)

2024-07-24 20:54 UTC, undead404 commented on src/content/learn/queueing-a-series-of-state-updates.md
> +Задання змінної стану ставить у чергу ще один рендер. Проте іноді може викинути потреба виконати кілько операцій над значенням, перш ніж додавати до черги новий рендер. Щоб це зробити, корисно розумі
1. Так усі пишуть, тому давай поки вважати, що це ок
2. Мені ваша вигадка зі "групує" подобається, щонайменше в цьому рядку – точно підходить як є.

2024-07-24 20:54 UTC, undead404 commented on src/content/learn/queueing-a-series-of-state-updates.md
> +Це дає змогу оновлювати кілька змінних стану — навіть з різних компонентів — не запускаючи забагато [повторних рендерів.](/learn/render-and-commit#re-renders-when-state-updates) Але це також означає,
Можливо, в пропозиції помилка?
```suggestion
Це дає змогу оновлювати кілька змінних стану — навіть із різних компонентів — не запускаючи забагато [повторних рендерів.](/learn/render-and-commit#re-renders-when-state-updates) Але це також означає, що UI оновиться лише _після_ завершення вашого обробника події та всього коду з нього. Така логіка, також відома як **групування,** значно пришвидшує ваш застосунок React. Також це позбавляє потреби мати справу з безглуздими "напівготовими" рендерами, в яких оновилась лише частина змінних.
```

2024-07-24 20:54 UTC, undead404 commented on src/content/learn/queueing-a-series-of-state-updates.md
> +Тут `n => n + 1` зветься **функцією-оновлювачем.** Коли ви передаєте її до сетера стану:
Мені здається, "функція задання стану" – нежиттєздатна конструкція...

2024-07-24 20:54 UTC, undead404 commented on src/content/learn/queueing-a-series-of-state-updates.md
> +### Що станеться, якщо замінити стан, перед тим оновивши його {/*what-happens-if-you-replace-state-after-updating-it*/}
```suggestion
### Що відбудеться, якщо замінити стан, перед тим оновивши його {/*what-happens-if-you-replace-state-after-updating-it*/}
```

2024-07-24 20:54 UTC, undead404 commented on src/content/learn/queueing-a-series-of-state-updates.md
> +Ви працюєте над застосунком мистецького торгівельного майданчика, що дає користувачам змогу розміщати кілька замовлень щодо одного предмету мистецтва водночас. Щоразу, коли користувач натискає кнопку
Та ні. Може бути "Очікуються"... Але це гірше виходить, на мій смак

2024-07-25 12:27 UTC, alinkedd commented on src/content/learn/queueing-a-series-of-state-updates.md
> +Це дає змогу оновлювати кілька змінних стану — навіть з різних компонентів — не запускаючи забагато [повторних рендерів.](/learn/render-and-commit#re-renders-when-state-updates) Але це також означає,
```suggestion
Це дає змогу оновлювати кілька змінних стану — навіть із різних компонентів — не запускаючи забагато [повторних рендерів.](/learn/render-and-commit#re-renders-when-state-updates) Але це також означає, що UI не оновиться _до_ завершення вашого обробника події та всього коду з нього. Така логіка, також відома як **групування,** значно пришвидшує ваш застосунок на React. Також це позбавляє потреби мати справу з безглуздими "напівготовими" рендерами, в яких оновилась лише частина змінних.
```

2024-07-25 12:28 UTC, alinkedd commented on src/content/learn/queueing-a-series-of-state-updates.md
> +Це дає змогу оновлювати кілька змінних стану — навіть з різних компонентів — не запускаючи забагато [повторних рендерів.](/learn/render-and-commit#re-renders-when-state-updates) Але це також означає,
або твоє, або моє останнє

2024-07-25 12:29 UTC, alinkedd commented on src/content/learn/queueing-a-series-of-state-updates.md
> +Тут `n => n + 1` зветься **функцією-оновлювачем.** Коли ви передаєте її до сетера стану:
там всього 16 використань слова setter, хай буде функція задання

2024-07-25 12:30 UTC, alinkedd commented on src/content/learn/queueing-a-series-of-state-updates.md
> +Ви працюєте над застосунком мистецького торгівельного майданчика, що дає користувачам змогу розміщати кілька замовлень щодо одного предмету мистецтва водночас. Щоразу, коли користувач натискає кнопку
ну ок

2024-07-25 12:32 UTC, alinkedd commented on src/content/learn/queueing-a-series-of-state-updates.md
> +Тут `n => n + 1` зветься **функцією-оновлювачем.** Коли ви передаєте її до сетера стану:
чи ти хочеш фукнцію оновлення?

2024-07-25 12:33 UTC, alinkedd commented on src/content/learn/queueing-a-series-of-state-updates.md
> +Тут `n => n + 1` зветься **функцією-оновлювачем.** Коли ви передаєте її до сетера стану:
просто функція оновлення - це функція як параметр функції задання
https://uk.legacy.reactjs.org/docs/faq-state.html

2024-07-25 12:49 UTC, undead404 commented on src/content/learn/queueing-a-series-of-state-updates.md
> +Тут `n => n + 1` зветься **функцією-оновлювачем.** Коли ви передаєте її до сетера стану:
Ну тоді най буде. Це в нас на WebDoky це слово зустрічається мільйон разів, ми вирішили не перекладати

2024-07-25 21:35 UTC, alinkedd approved these changes

2024-07-25 21:35 UTC, merged