Finished translation of Profiler page
reactjs/uk.react.dev pull request #564
Opened 2024-09-01 20:43 UTC by GeorgeShvab

Переклав "profiling" як "профілювання"

2024-09-07 15:53 UTC, alinkedd requested changes
Я ще обдумаю "коміт", бо [тут](https://github.com/reactjs/uk.react.dev/pull/534/files) було перекладено як фіксація, але поки немає остаточного рішення

2024-09-07 15:53 UTC, alinkedd commented on src/content/reference/react/Profiler.md
> +* Профілювання створює додаткове навантаження, тому **воно вимкнене в продакшн-збірці за замовчуванням.** Щоб увімкнути продакшн-профілювання, потрібно скористатися [спеціальною продакшн-збіркою з пр
```suggestion
* Профілювання створює додаткове навантаження, тому **початково воно вимкнене у збірці для впровадження (production).** Щоб профілювати у публічному середовищі, потрібно скористатися [спеціальною збіркою для впровадження з увімкненим профілюванням.](https://fb.me/react-profiling)
```
- за замовчуванням - калька, ось тут є варіанти https://onlinecorrector.com.ua/uk/%D1%82%D0%B8%D0%BF%D0%BE%D0%B2%D0%B8%D0%B9-%D1%81%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82%D0%BD%D0%B8%D0%B9-%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D0%B8%D0%B9/, а також у webdoky ще вживають `усталено`
- продакшн - впроваджений, готовий до впровадження, доступний для користувача, у публічному/реальному середовищі

2024-09-07 15:53 UTC, alinkedd commented on src/content/reference/react/Profiler.md
> +* `id`: Рядковий `id` проп дерева `<Profiler>`, яке щойно було закомічено. Він дозволяє вам визначити, яку частину дерева було закомічено, якщо ви використовуєте кілька профілювачів.
```suggestion
* `id`: Стрічковий проп `id` дерева `<Profiler>`, яке щойно було закомічено. Він дозволяє вам визначити, яку частину дерева було закомічено, якщо ви використовуєте кілька профілювачів.
```

2024-09-07 15:53 UTC, alinkedd commented on src/content/reference/react/Profiler.md
> +* `phase`: `"mount"`, `"update"` або `"nested-update"`. Дає змогу дізнатися, чи дерево було щойно змонтовано вперше, або ж перерендерено через зміни в стані, пропсах чи хуках.
```suggestion
* `phase`: `"mount"`, `"update"` або `"nested-update"`. Дає змогу дізнатися, чи дерево було щойно змонтовано вперше або ж рендерено повторно через зміни в стані, пропсах чи хуках.
```

2024-09-07 15:53 UTC, alinkedd commented on src/content/reference/react/Profiler.md
> +* `actualDuration`: Кількість мілісекунд, витрачених на рендеринг компонента `<Profiler>` і його дочірніх компонентів під час поточного оновлення. Вказуєте на те, наскільки ефективно субдерево викори
```suggestion
* `actualDuration`: Кількість мілісекунд, витрачених на рендеринг компонента `<Profiler>` і його дочірніх компонентів під час поточного оновлення. Вказує на те, наскільки ефективно піддерево використовує мемоїзацію (наприклад, [`memo`](/reference/react/memo) і [`useMemo`](/reference/react/useMemo)). В ідеалі, це значення повинно значно зменшитися після першого монтування, оскільки багато з дочірніх компонентів буде перерендерюватися лише за зміни пропсів.
```

якщо підмет - це збірне слово з додатками, то присудок узгоджується саме з підметом, а не з додатками: багато буде, а не багато будуть

2024-09-07 15:53 UTC, alinkedd commented on src/content/reference/react/Profiler.md
> +* `baseDuration`: Кількість мілісекунд, яка відображає, скільки часу займе повторний рендер усього субдерева компонента `<Profiler>` без будь-якої оптимізації. Це значення розраховується як сума часу
```suggestion
* `baseDuration`: Кількість мілісекунд, яка відображає, скільки часу займе повторний рендер усього піддерева компонента `<Profiler>` без будь-якої оптимізації. Це значення розраховується як сума часу останніх рендерів кожного компонента в дереві. Воно показує найгірший сценарій рендерингу (наприклад, перше монтування або дерево без мемоїзації). Порівняйте `actualDuration` з ним, щоби перевірити, чи працює мемоїзація.
```

2024-09-07 15:53 UTC, alinkedd commented on src/content/reference/react/Profiler.md
> +Він потребує двох пропсів: `id` (рядок) і функцію зворотного виклику `onRender` (функція), яку React викличе, коли будь-який компонент всередині дерева "закомітить" оновлення.
```suggestion
Він потребує двох пропсів: `id` (стрічка) і функцію зворотного виклику `onRender`, яку React викличе, коли будь-який компонент всередині дерева "закомітить" оновлення.
```

2024-09-07 15:53 UTC, alinkedd commented on src/content/reference/react/Profiler.md
> +* Профілювання створює додаткове навантаження, тому **воно вимкнене в продакшн-збірці за замовчуванням.** Щоб увімкнути продакшн-профілювання, потрібно скористатися [спеціальною продакшн-збіркою з пр
```suggestion
* Профілювання створює додаткове навантаження, тому **початково воно вимкнене у збірці для впровадження (production).** Щоб профілювати у публічному середовищі, потрібно скористатися [спеціальною збіркою для впровадження з увімкненим профілюванням.](https://fb.me/react-profiling)
```

2024-09-07 15:53 UTC, alinkedd commented on src/content/reference/react/Profiler.md
> +`<Profiler>` дозволяє вам збирати показники програмно. Якщо ви шукаєте інтерактивний профілювач, спробуйте вкладку Profiler у [Інструментах React розробника](/learn/react-developer-tools). Вона надає
```suggestion
`<Profiler>` дає вам змогу збирати показники програмно. Якщо ви шукаєте інтерактивний профілювач, спробуйте вкладку Profiler в [Інструментах React розробника](/learn/react-developer-tools). Вона надає подібний функціонал як розширення для браузера.
```
- `у вигляді` краще замінити https://onlinecorrector.com.ua/uk/%D0%BF%D0%BE%D0%B4%D1%96%D0%B1%D0%BD%D0%B8%D0%B9-%D0%B4%D0%BE-%D1%8F%D0%BA/

2024-09-11 11:34 UTC, alinkedd requested changes
Based on https://github.com/reactjs/uk.react.dev/pull/534/files#r1754064941:
- Фаза - коміт
- Набір змін - коміт
- але замість комітити - внести (зміни/оновлення)

Також у попередньому review вже змінила відповідні переклади

2024-09-11 11:34 UTC, alinkedd commented on src/content/reference/react/Profiler.md
> +* `commitTime`: Числове значення, яке вказує на момент часу, коли React закомітив поточне оновлення. Це значення однакове в усіх профілювачів у коміті, що дає змогу згрупувати їх за потреби.
```suggestion
* `commitTime`: Числове значення, яке вказує на момент часу, коли React вніс поточне оновлення. Це значення однакове в усіх профілювачів у коміті, що дає змогу згрупувати їх за потреби.
```

2024-09-26 07:06 UTC, GeorgeShvab commented
Дякую за рев'ю! Ознайомився з коментарями, виправив усе та об'єднав зміни в один коміт.

2024-09-29 15:24 UTC, alinkedd requested changes

2024-09-29 15:24 UTC, alinkedd commented on src/content/reference/react/Profiler.md
> +Хоча `<Profiler>` є легким компонентом, його слід використовувати лише за необхідності. Кожне його використання додає певне навантаження на CPU та пам’ять вашого застосунку.
```suggestion
Хоча `<Profiler>` є легким компонентом, його слід використовувати лише за необхідності. Кожне його використання додає певне навантаження на CPU та пам'ять вашого застосунку.
```

2024-09-29 15:25 UTC, alinkedd approved these changes

2024-09-29 15:27 UTC, merged