Finish translation of Reacting to Input with State
reactjs/uk.react.dev pull request #581
Opened 2024-12-29 20:27 UTC by undead404

2025-01-02 22:20 UTC, alinkedd requested changes
Перша частина перевірки (до step 3)

- trigger поки залишаю як запустити/запуск #584
- represent поки залишаю як представляти

2025-01-02 22:20 UTC, alinkedd commented on src/content/learn/reacting-to-input-with-state.md
> +        В якому місті є білборд, що перетворює повітря на питну воду?
```suggestion
        У якому місті є білборд, що перетворює повітря на питну воду?
```

2025-01-02 22:20 UTC, alinkedd commented on src/content/learn/reacting-to-input-with-state.md
> +Цей проп можна назвати як завгодно, назва тут неважлива. Спробуйте змінити `status = 'empty'` на `status = 'success'`, щоб побачити появу повідомлення про успіх. Імітування дає змогу швидко ітерувати
```suggestion
Цей проп можна назвати як завгодно, назва тут неважлива. Спробуйте замінити `status = 'empty'` на `status = 'success'`, щоб побачити появу повідомлення про успіх. Макетування дає змогу швидко ітеруватися в розробці UI перед під'єднанням будь-якої логіки. Ось змістовніший прототип того самого компонента, так само "контрольований" пропом `status`:
```

2025-01-02 22:20 UTC, alinkedd commented on src/content/learn/reacting-to-input-with-state.md
> +        В якому місті є білборд, що перетворює повітря на питну воду?
```suggestion
        У якому місті є білборд, що перетворює повітря на питну воду?
```

2025-01-02 22:20 UTC, alinkedd commented on src/content/learn/reacting-to-input-with-state.md
>  If a component has a lot of visual states, it can be convenient to show them all on one page:
```suggestion
Якщо компонент має багато візуальних станів, було б зручніше показати їх на одній сторінці:
```

2025-01-02 22:20 UTC, alinkedd commented on src/content/learn/reacting-to-input-with-state.md
> +Сторінки, схожі на цю, нерідко звуть "живими стилістичними настановами" або "сторібуками".
```suggestion
Сторінки, схожі на цю, нерідко звуть "живими стилістичними настановами" ("living styleguides") або "сторибуками" ("storybooks").
```

2025-01-02 22:20 UTC, alinkedd commented on src/content/learn/reacting-to-input-with-state.md
> +Щоб легше візуалізувати ці переходи, спробуйте намалювати кожний стан на папері, у вигляді підписаного кружальця, а кожну зміну між двома станами — стрілкою. Ви можете накреслити так чимало переходів
```suggestion
Щоб легше візуалізувати ці переходи, спробуйте намалювати кожний стан на папері як підписане коло, а кожну зміну між двома станами — стрілкою. Так ви можете накреслити чимало переходів і знайти дефекти задовго до початку реалізації.
```

2025-01-02 22:20 UTC, alinkedd commented on src/content/learn/reacting-to-input-with-state.md
> +<Diagram name="responding_to_input_flow" height={350} width={688} alt="Діаграма з руком зліва направо, що має 5 вузлів. Перший вузол підписаний 'empty' і має стрілку, підписану 'start typing' (почато
```suggestion
<Diagram name="responding_to_input_flow" height={350} width={688} alt="Діаграма зліва направо, що має 5 вузлів. Перший вузол підписаний 'Empty' (порожній) і має стрілку, підписану 'Start typing' (початок друку), сполучену з вузлом, підписаним 'Submitting' (надсилання), з якого виходять дві стрілки. Стрілка ліворуч підписана 'Network error' (мережева помилка) і сполучає з вузлом, підписаним 'Error' (помилка). Стрілка праворуч підписана 'Network success' (мережевий успіх) і сполучає з вузлом, підписаним 'Success' (успіх).">
```

2025-01-03 12:11 UTC, undead404 commented on src/content/learn/reacting-to-input-with-state.md
> +* Коли ви натискаєте "Надіслати", то і форма, і кнопка **стають вимкненими,** і **з'являється** дзиґа.
Чим ти не вподобала дзиґу(((

2025-01-03 12:15 UTC, undead404 commented
Звертаю увагу, що лишилась незакрита дискусія

2025-01-03 12:22 UTC, alinkedd commented on src/content/learn/reacting-to-input-with-state.md
> +Як і дизайнеру, вам захочеться "окреслити" чи "створити імітації" різних станів, перш ніж додавати логіку. Наприклад, ось імітація суто візуальної частини форми. Ця імітація контролюється пропом `sta
1) https://uk.wikipedia.org/wiki/%D0%9C%D0%B0%D0%BA%D0%B5%D1%82_%D0%BE%D0%B1%27%D1%94%D0%BA%D1%82%D0%B0
2) https://github.com/reactjs/uk.react.dev/blob/main/TRANSLATION.md?plain=1#L154

2025-01-03 12:23 UTC, alinkedd commented on src/content/learn/reacting-to-input-with-state.md
> +Цей проп можна назвати як завгодно, назва тут неважлива. Спробуйте змінити `status = 'empty'` на `status = 'success'`, щоб побачити появу повідомлення про успіх. Імітування дає змогу швидко ітерувати
https://github.com/reactjs/uk.react.dev/pull/581#discussion_r1901736386

2025-01-06 18:08 UTC, alinkedd requested changes
Друга і фінальна частина перевірки

trigger змінено на тригер/збудити

2025-01-06 18:08 UTC, alinkedd commented on src/content/learn/reacting-to-input-with-state.md
> +Уявіть, що React не існує. Чи можна відрефакторити цей код у такий спосіб, що зробить логіку надійнішою та більш подібною на варіант з React? На що це було б схоже, якби стан був явним, неначе в Reac
```suggestion
Уявіть, що React не існує. Чи можна відрефакторити цей код у такий спосіб, що зробить логіку надійнішою та більш подібною на варіант із React? На що це було б схоже, якби стан був явним, неначе в React?
```

2025-01-06 18:08 UTC, alinkedd commented on src/content/learn/reacting-to-input-with-state.md
> +Якщо вам важко зрозуміти, з чого почати, то заготовка нижче містить більшість структури. Якщо починаєте з неї, то додайте логіку, якої не вистачає, в функції `updateDOM`. (Звіряйтеся з вихідним кодом
```suggestion
Якщо вам важко зрозуміти, з чого почати, то заготовка нижче містить більшість структури. Якщо починаєте з неї, то додайте логіку, якої не вистачає, у функції `updateDOM`. (Звіряйтеся з вихідним кодом, коли знадобиться.)
```

2025-01-06 18:08 UTC, alinkedd commented on src/content/learn/reacting-to-input-with-state.md
> +</Challenges>
що тут змінилося? забрав каретку?

2025-01-06 18:08 UTC, alinkedd commented on src/content/learn/reacting-to-input-with-state.md
> +2. **Визначте**, що запускає ці зміни стану
```suggestion
2. **Визначте**, що збуджує ці зміни стану
```

2025-01-06 18:08 UTC, alinkedd commented on src/content/learn/reacting-to-input-with-state.md
> +Запускати зміни стану можна у відповідь на два види введення:
```suggestion
Збудити зміни стану можна у відповідь на два види введення:
```

2025-01-06 18:08 UTC, alinkedd commented on src/content/learn/reacting-to-input-with-state.md
> +### Крок 2. Визначте, що запускає ці зміни стану {/*step-2-determine-what-triggers-those-state-changes*/}
```suggestion
### Крок 2. Визначте, що збуджує ці зміни стану {/*step-2-determine-what-triggers-those-state-changes*/}
```

2025-01-06 18:08 UTC, alinkedd commented on src/content/learn/reacting-to-input-with-state.md
> +  2. Визначте людські та комп'ютерні пускачі змін стану.
```suggestion
  2. Визначте людські та комп'ютерні тригери змін стану.
```

2025-01-14 08:27 UTC, undead404 reviewed
Не подобаються деякі зміни, наприклад, слово "редюсер". І якщо "to trigger" це "збудити", то "a trigger" міг би бути "збудником".

Але впиратися не буду

2025-01-14 08:27 UTC, undead404 commented on src/content/learn/reacting-to-input-with-state.md
> +</Challenges>
Щиро кажучи, не знаю. Можливо, редактор автоматично змінив щось щодо останнього символа

2025-01-14 21:12 UTC, alinkedd commented on src/content/learn/reacting-to-input-with-state.md
> +</Challenges>
```suggestion
</Challenges>

```

2025-01-14 21:15 UTC, alinkedd approved these changes

2025-01-14 21:16 UTC, merged